In [4]:
import pandas as pd
df = pd.read_csv('data/ibtracs.since1980.list.v04r00.csv', dtype='object')

,SID,SEASON,NUMBER,BASIN,SUBBASIN,NAME,ISO_TIME,NATURE,LAT,LON,...,BOM_GUST_PER,REUNION_GUST,REUNION_GUST_PER,USA_SEAHGT,USA_SEARAD_NE,USA_SEARAD_SE,USA_SEARAD_SW,USA_SEARAD_NW,STORM_SPEED,STORM_DIR
0,,Year,,,,,,,degrees_north,degrees_east,...,second,kts,second,ft,nmile,nmile,nmile,nmile,kts,degrees
1,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 00:00:00,TS,-12.5000,172.500,...,,,,,,,,,6,351
2,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 03:00:00,TS,-12.1927,172.441,...,,,,,,,,,6,351
3,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 06:00:00,TS,-11.9144,172.412,...,,,,,,,,,5,358
4,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 09:00:00,TS,-11.6863,172.435,...,,,,,,,,,4,12

In [5]:
df.drop(index=0, inplace=True)
df.shape

In [6]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 271883 entries, 1 to 271883
Data columns (total 163 columns):
SID                 object
SEASON              object
NUMBER              object
BASIN               object
SUBBASIN            object
NAME                object
ISO_TIME            object
NATURE              object
LAT                 object
LON                 object
WMO_WIND            object
WMO_PRES            object
WMO_AGENCY          object
TRACK_TYPE          object
DIST2LAND           object
LANDFALL            object
IFLAG               object
USA_AGENCY          object
USA_ATCF_ID         object
USA_LAT             object
USA_LON             object
USA_RECORD          object
USA_STATUS          object
USA_WIND            object
USA_PRES            object
USA_SSHS            object
USA_R34_NE          object
USA_R34_SE          object
USA_R34_SW          object
USA_R34_NW          object
USA_R50_NE          object
USA_R50_SE          object
USA_R50_SW          object
USA_R50_NW          object
USA_R64_NE          object
USA_R64_SE          object
USA_R64_SW          object
USA_R64_NW          object
USA_POCI            object
USA_ROCI            object
USA_RMW             object
USA_EYE             object
TOKYO_LAT           object
TOKYO_LON           object
TOKYO_GRADE         object
TOKYO_WIND          object
TOKYO_PRES          object
TOKYO_R50_DIR       object
TOKYO_R50_LONG      object
TOKYO_R50_SHORT     object
TOKYO_R30_DIR       object
TOKYO_R30_LONG      object
TOKYO_R30_SHORT     object
TOKYO_LAND          object
CMA_LAT             object
CMA_LON             object
CMA_CAT             object
CMA_WIND            object
CMA_PRES            object
HKO_LAT             object
HKO_LON             object
HKO_CAT             object
HKO_WIND            object
HKO_PRES            object
NEWDELHI_LAT        object
NEWDELHI_LON        object
NEWDELHI_GRADE      object
NEWDELHI_WIND       object
NEWDELHI_PRES       object
NEWDELHI_CI         object
NEWDELHI_DP         object
NEWDELHI_POCI       object
REUNION_LAT         object
REUNION_LON         object
REUNION_TYPE        object
REUNION_WIND        object
REUNION_PRES        object
REUNION_TNUM        object
REUNION_CI          object
REUNION_RMW         object
REUNION_R34_NE      object
REUNION_R34_SE      object
REUNION_R34_SW      object
REUNION_R34_NW      object
REUNION_R50_NE      object
REUNION_R50_SE      object
REUNION_R50_SW      object
REUNION_R50_NW      object
REUNION_R64_NE      object
REUNION_R64_SE      object
REUNION_R64_SW      object
REUNION_R64_NW      object
BOM_LAT             object
BOM_LON             object
BOM_TYPE            object
BOM_WIND            object
BOM_PRES            object
BOM_TNUM            object
BOM_CI              object
BOM_RMW             object
BOM_R34_NE          object
BOM_R34_SE          object
BOM_R34_SW          object
BOM_R34_NW          object
BOM_R50_NE          object
BOM_R50_SE          object
BOM_R50_SW          object
BOM_R50_NW          object
BOM_R64_NE          object
BOM_R64_SE          object
BOM_R64_SW          object
BOM_R64_NW          object
BOM_ROCI            object
BOM_POCI            object
BOM_EYE             object
BOM_POS_METHOD      object
BOM_PRES_METHOD     object
NADI_LAT            object
NADI_LON            object
NADI_CAT            object
NADI_WIND           object
NADI_PRES           object
WELLINGTON_LAT      object
WELLINGTON_LON      object
WELLINGTON_WIND     object
WELLINGTON_PRES     object
DS824_LAT           object
DS824_LON           object
DS824_STAGE         object
DS824_WIND          object
DS824_PRES          object
TD9636_LAT          object
TD9636_LON          object
TD9636_STAGE        object
TD9636_WIND         object
TD9636_PRES         object
TD9635_LAT          object
TD9635_LON          object
TD9635_WIND         object
TD9635_PRES         object
TD9635_ROCI         object
NEUMANN_LAT         object
NEUMANN_LON         object
NEUMANN_CLASS       object
NEUMANN_WIND        object
NEUMANN_PRES        object
MLC_LAT             object
MLC_LON             object
MLC_CLASS           object
MLC_WIND            object
MLC_PRES            object
USA_GUST            object
BOM_GUST            object
BOM_GUST_PER        object
REUNION_GUST        object
REUNION_GUST_PER    object
USA_SEAHGT          object
USA_SEARAD_NE       object
USA_SEARAD_SE       object
USA_SEARAD_SW       object
USA_SEARAD_NW       object
STORM_SPEED         object
STORM_DIR           object
dtypes: object(163)
memory usage: 340.2+ MB

In [7]:
#there are this many separate storms
df['SID'].nunique()

4458

In [20]:
df['NATURE'].value_counts()
# remove nr - not reported and mx - mixture
# severe storm (class 1)= TS, non severe (class 0) = ET extratropical, DS disturbance, SS subtropical

TS    203150
NR     42552
ET     13450
DS      8218
MX      2908
SS      1605
Name: NATURE, dtype: int64

In [25]:
storm_class = df[['SID', 'NATURE']]
storm_class = storm_class.groupby(by='SID', axis=0)
storm_class

In [11]:
pd.set_option('display.max_columns', None)
df.head()

,SID,SEASON,NUMBER,BASIN,SUBBASIN,NAME,ISO_TIME,NATURE,LAT,LON,WMO_WIND,WMO_PRES,WMO_AGENCY,TRACK_TYPE,DIST2LAND,LANDFALL,IFLAG,USA_AGENCY,USA_ATCF_ID,USA_LAT,USA_LON,USA_RECORD,USA_STATUS,USA_WIND,USA_PRES,USA_SSHS,USA_R34_NE,USA_R34_SE,USA_R34_SW,USA_R34_NW,USA_R50_NE,USA_R50_SE,USA_R50_SW,USA_R50_NW,USA_R64_NE,USA_R64_SE,USA_R64_SW,USA_R64_NW,USA_POCI,USA_ROCI,USA_RMW,USA_EYE,TOKYO_LAT,TOKYO_LON,TOKYO_GRADE,TOKYO_WIND,TOKYO_PRES,TOKYO_R50_DIR,TOKYO_R50_LONG,TOKYO_R50_SHORT,TOKYO_R30_DIR,TOKYO_R30_LONG,TOKYO_R30_SHORT,TOKYO_LAND,CMA_LAT,CMA_LON,CMA_CAT,CMA_WIND,CMA_PRES,HKO_LAT,HKO_LON,HKO_CAT,HKO_WIND,HKO_PRES,NEWDELHI_LAT,NEWDELHI_LON,NEWDELHI_GRADE,NEWDELHI_WIND,NEWDELHI_PRES,NEWDELHI_CI,NEWDELHI_DP,NEWDELHI_POCI,REUNION_LAT,REUNION_LON,REUNION_TYPE,REUNION_WIND,REUNION_PRES,REUNION_TNUM,REUNION_CI,REUNION_RMW,REUNION_R34_NE,REUNION_R34_SE,REUNION_R34_SW,REUNION_R34_NW,REUNION_R50_NE,REUNION_R50_SE,REUNION_R50_SW,REUNION_R50_NW,REUNION_R64_NE,REUNION_R64_SE,REUNION_R64_SW,REUNION_R64_NW,BOM_LAT,BOM_LON,BOM_TYPE,BOM_WIND,BOM_PRES,BOM_TNUM,BOM_CI,BOM_RMW,BOM_R34_NE,BOM_R34_SE,BOM_R34_SW,BOM_R34_NW,BOM_R50_NE,BOM_R50_SE,BOM_R50_SW,BOM_R50_NW,BOM_R64_NE,BOM_R64_SE,BOM_R64_SW,BOM_R64_NW,BOM_ROCI,BOM_POCI,BOM_EYE,BOM_POS_METHOD,BOM_PRES_METHOD,NADI_LAT,NADI_LON,NADI_CAT,NADI_WIND,NADI_PRES,WELLINGTON_LAT,WELLINGTON_LON,WELLINGTON_WIND,WELLINGTON_PRES,DS824_LAT,DS824_LON,DS824_STAGE,DS824_WIND,DS824_PRES,TD9636_LAT,TD9636_LON,TD9636_STAGE,TD9636_WIND,TD9636_PRES,TD9635_LAT,TD9635_LON,TD9635_WIND,TD9635_PRES,TD9635_ROCI,NEUMANN_LAT,NEUMANN_LON,NEUMANN_CLASS,NEUMANN_WIND,NEUMANN_PRES,MLC_LAT,MLC_LON,MLC_CLASS,MLC_WIND,MLC_PRES,USA_GUST,BOM_GUST,BOM_GUST_PER,REUNION_GUST,REUNION_GUST_PER,USA_SEAHGT,USA_SEARAD_NE,USA_SEARAD_SE,USA_SEARAD_SW,USA_SEARAD_NW,STORM_SPEED,STORM_DIR
1,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 00:00:00,TS,-12.5000,172.500,,,,main,647,647,O________OO_O_,jtwc_sh,SH051980,-12.5000,172.500,,,25,,-1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-12.5000,172.500,TC,25,,-12.5000,172.500,1,25,,,,,,,-12.5000,172.500,TC,25,,,,,,,,,,,,,,,,,6,351
2,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 03:00:00,TS,-12.1927,172.441,,,,main,653,653,P________PP_P_,,SH051980,-12.1825,172.432,,,25,,-1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-12.1825,172.432,TC,25,,-12.2234,172.469,1,,,,,,,,-12.1825,172.432,TC,25,,,,,,,,,,,,,,,,,6,351
3,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 06:00:00,TS,-11.9144,172.412,,,,main,670,670,O________OP_O_,jtwc_sh,SH051980,-11.9000,172.400,,,25,,-1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-11.9000,172.400,TC,25,,-11.9575,172.450,1,,,,,,,,-11.9000,172.400,TC,25,,,,,,,,,,,,,,,,,5,358
4,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 09:00:00,TS,-11.6863,172.435,,,,main,682,682,P________PP_P_,,SH051980,-11.6775,172.428,,,25,,-1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-11.6775,172.428,TC,25,,-11.7128,172.456,1,,,,,,,,-11.6775,172.428,TC,25,,,,,,,,,,,,,,,,,4,12
5,1980001S13173,1980,1,SP,MM,PENI,1980-01-01 12:00:00,TS,-11.5000,172.500,,,,main,703,703,O________OO_O_,jtwc_sh,SH051980,-11.5000,172.500,,,25,,-1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-11.5000,172.500,TC,25,,-11.5000,172.500,1,,,,,,,,-11.5000,172.500,TC,25,,,,,,,,,,,,,,,,,4,22

In [28]:
initial_feats = ['SID', 'SEASON', 'NUMBER', 'BASIN', 'SUBBASIN', 'ISO_TIME', 'LAT', 'LON', 'WMO_WIND', 'DIST2LAND', 'DS824_WIND', 'TD9636_STAGE', 'STORM_SPEED', 'STORM_DIR']
inital_target = df['NATURE']

In [33]:
xs_df = df[initial_feats]
xs_df.head()

,SID,SEASON,NUMBER,BASIN,SUBBASIN,ISO_TIME,LAT,LON,WMO_WIND,DIST2LAND,DS824_WIND,TD9636_STAGE,STORM_SPEED,STORM_DIR
1,1980001S13173,1980,1,SP,MM,1980-01-01 00:00:00,-12.5000,172.500,,647,25,1,6,351
2,1980001S13173,1980,1,SP,MM,1980-01-01 03:00:00,-12.1927,172.441,,653,25,1,6,351
3,1980001S13173,1980,1,SP,MM,1980-01-01 06:00:00,-11.9144,172.412,,670,25,1,5,358
4,1980001S13173,1980,1,SP,MM,1980-01-01 09:00:00,-11.6863,172.435,,682,25,1,4,12
5,1980001S13173,1980,1,SP,MM,1980-01-01 12:00:00,-11.5000,172.500,,703,25,1,4,22

In [66]:
xs_df[['NUMBER', 'LAT', 'LON', 'DIST2LAND']] = xs_df[['NUMBER', 'LAT', 'LON', 'DIST2LAND']].apply(pd.to_numeric)
xs_df[['SEASON', 'ISO_TIME']] = xs_df[['SEASON', 'ISO_TIME']].apply(pd.to_datetime)

C:\Users\christina.sarver\Anaconda3\envs\learn-env\lib\site-packages\pandas\core\frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [68]:
string_cols = ['SID', 'BASIN', 'SUBBASIN']

In [69]:
remaining_cols = ['WMO_WIND', 'DIST2LAND', 'DS824_WIND', 'TD9636_STAGE', 'STORM_SPEED', 'STORM_DIR']
xs_df[remaining_cols].apply(pd.to_numeric)

ValueError: ('Unable to parse string " " at position 0', 'occurred at index WMO_WIND')

In [72]:
xs_df['WMO_WIND'][1]

' '

In [67]:
xs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 271883 entries, 1 to 271883
Data columns (total 14 columns):
SID             271883 non-null object
SEASON          271883 non-null datetime64[ns]
NUMBER          271883 non-null int64
BASIN           235582 non-null object
SUBBASIN        242727 non-null object
ISO_TIME        271883 non-null datetime64[ns]
LAT             271883 non-null float64
LON             271883 non-null float64
WMO_WIND        271883 non-null object
DIST2LAND       271883 non-null int64
DS824_WIND      271883 non-null object
TD9636_STAGE    271883 non-null object
STORM_SPEED     271883 non-null object
STORM_DIR       271883 non-null object
dtypes: datetime64[ns](2), float64(2), int64(2), object(8)
memory usage: 41.1+ MB